### ISSUE TITLE
We couldn't get a response for you, please try again

### ISSUE THREAD

**Issue by khlsvr** [rj1/chatgpt-irc#1]
python chatgpt-irc.py 
None
-> NICK chatgpt
-> USER chatgpt * * :chatgpt
-> JOIN #acro
[#acro] \<oo\> chatgpt: hi
-> PRIVMSG #acro :oo: hold on, I'm thinking..
-> PRIVMSG #acro :oo: We couldn't get a response for you, please try again
-> PONG irc.atw-inter.net

In the network tab I first activate the lower item called "conversation" of the two. The above one doesn't have a conversation_id. Then I copy the values to my config.json. Then I connect it to ircnet room and it connects fine. When I message to it, it catches that problem like above.

Beginner mistake. I had the Bearer included in the token which was not allowed there, fixed.

**Comment by rj1** [comment]
I pushed an update that removes the requirement for conversation_id
in the config

Quoting khlsvr (2022-12-08 11:20:33)

**Comment by Kitu83** [comment]
I have the same problem...
