### ISSUE TITLE
No response from chat-gtp on irc

### ISSUE THREAD

**Issue by madvip3r** [rj1/chatgpt-irc#4]
Config. json set up by steps in the README.md configuration
Started and it's connect to an IRC server and join the channel
When user type something in channel, it's shown in console of chatgpt-irc
There is no response

**Comment by Strykar** [comment]
@rj1 Perhaps adding exact actual examples in the README for the `auth_token` and `cookie` might help.

**Comment by cleobuline** [comment]
the robot connect correctly seem to parse the lines well , but yi get alwais the same response 
<turlupine> chatgpt: Why the sky is blue ?
<chatgpt> turlupine: hold on, I'm thinking..
<chatgpt> turlupine: We couldn't get a response for you, please try again

**Comment by rj1** [comment]
please ensure you're adding the auth token, user agent, and cookie to the config.json file
