### ISSUE TITLE
Typical problems

### ISSUE THREAD

**Issue by moonlightz** [rj1/chatgpt-irc#5]
Background: I myself heard about chatgpt over the tech news and some people having fun with it but I remained skeptical to use it. Today, I wanted something that could connect to irc because someone in a youtube chat said it is possible. So, searched chatgpt irc and this github project was the first.
First of all, thanks for the attempt to write something. It's not everyone that can do it.
Second, I find this project a bare minimum. I'm simply kind of lost. The bare readme needs to be improved with things like what's needed (in this case python3), even more clearer instructions, the json and the script itself needs more editing like error catching, add to the readme the possible problems+fixes, running as background task.

I personally can't make this working yet and I spent at least 2 hours. I'm not a python developer.
I looked at the conf file, did the edits, launched it, the first error I got was SSL expiration. No big deal, I edited to connect the port 6667. Then, it was launched fine, but the bot didn't join to the channel because I just replaced erj1 with the name of the channel without including the #. Then it joined the channel but there is nowhen examples of interaction. I tried chatgpt hi or chatgpt, hi, and nothing. Then I saw here that would be chatgpt: hi. its response was it was thinking and crashes about an unicode issue that I can't seem to solve.
And now I am stuck.

**Comment by IPutMyDogInAnIndustrialFan** [comment]
did you write this with chatgpt?

**Comment by rj1** [comment]
> I find this project a bare minimum.

this is intentional, it works well the way it is

> The bare readme needs to be improved with things like what's needed
> (in this case python3), even more clearer instructions

the instructions are clear I think, you simply paste header values from your
browser into the config file. maybe you could send a pull request to add
better instructions

> running as background task

you can do this yourself using something like a systemd service or
terminal multiplexer


hope you can get it working, it's fun!
