### ISSUE TITLE
Error Messages on IRC

### ISSUE THREAD

**Issue by gokturkyilmaz** [rj1/chatgpt-irc#6]
Hello,

I've installed chatgpt bot on IRC but it seem to be not working when type something getting error message like

[23:26] [chatgpt] Gokturk: hold on, I'm thinking..
[23:26] [chatgpt] Gokturk: We couldn't get a response for you, please try again

Any idea?

**Comment by rj1** [comment]
likely a configuration issue, please ensure you're copying the proper
values from your browser into config.json, and the cookie string likely
needs to be escaped as it contains quotes and other special characters

**Comment by gokturkyilmaz** [comment]
> likely a configuration issue, please ensure you're copying the proper values from your browser into config.json, and the cookie string likely needs to be escaped as it contains quotes and other special characters

The bot is on IRC but It's still not working, I am make sure of that my configs are correct. Btw, how to command the bot on IRC?Could you please check the configs: https://pastebin.blesmrt.net/?391eba899180c153#83KKYnxCFFdaA1c1hsx6cAZRrK1dKRQ2rvw34a6xkshc

**Comment by yybjy** [comment]
兄弟irc是啥呀，你这个程序是能直接在python里运行吗？
hi brother ,I don't konw,what is irc?,your this program can running in python?
why i couldn't run it,always show :
None
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\image\chatgpt-irc-144cd63944abf2433f3aa6a388d7f809bbb693c9\chatgpt-irc.py", line 234, in <module>
    asyncio.run(main_loop(**options))
  File "D:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\dell\Desktop\image\chatgpt-irc-144cd63944abf2433f3aa6a388d7f809bbb693c9\chatgpt-irc.py", line 162, in main_loop
    reader, writer = await asyncio.open_connection(
  File "D:\python\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "D:\python\lib\asyncio\base_events.py", line 1064, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [WinError 1225] 远程计算机拒绝网络连接。, [WinError 121] 信号灯超时时间已到
>>>

**Comment by rj1** [comment]
> The bot is on IRC but It's still not working, I am make sure of that my configs are correct. Btw, how to command the bot on IRC?Could you please check the configs: https://pastebin.blesmrt.net/?391eba899180c153#83KKYnxCFFdaA1c1hsx6cAZRrK1dKRQ2rvw34a6xkshc

remove "Bearer " from your auth token, or pull the latest update from the
repo, I have just pushed an update which allows you to include the
Bearer prefix

**Comment by rj1** [comment]
sorry, I don't know what this is. It looks like a Windows related error.
I recommend to run this software on Linux or FreeBSD.

Quoting 鱼香肉丝 (2023-02-05 03:19:12)
> 兄弟irc是啥呀，你这个程序是能直接在python里运行吗？
> hi brother ,I don't konw,what is irc?,your this program can running in python?
> why i couldn't run it,always show :
> None
> Traceback (most recent call last):
>   File "C:\Users\dell\Desktop\image\chatgpt-irc-144cd63944abf2433f3aa6a388d7f809bbb693c9\chatgpt-irc.py", line 234, in <module>
>     asyncio.run(main_loop(**options))
>   File "D:\python\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "D:\python\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "C:\Users\dell\Desktop\image\chatgpt-irc-144cd63944abf2433f3aa6a388d7f809bbb693c9\chatgpt-irc.py", line 162, in main_loop
>     reader, writer = await asyncio.open_connection(
>   File "D:\python\lib\asyncio\streams.py", line 52, in open_connection
>     transport, _ = await loop.create_connection(
>   File "D:\python\lib\asyncio\base_events.py", line 1064, in create_connection
>     raise OSError('Multiple exceptions: {}'.format(
> OSError: Multiple exceptions: [WinError 1225] 远程计算机拒绝网络连接。, [WinError 121] 信号灯超时时间已到
> >>>

**Comment by yybjy** [comment]
![image](https://user-images.githubusercontent.com/91821567/216812710-d3c6aed2-b8f4-4832-a581-0ba97dc74bdb.png)
my english may be not very wall,I use idle to run your chat-irc.py ,than it show that problem

**Comment by gokturkyilmaz** [comment]
> The bot is on IRC but It's still not working, I am make sure of that my configs are correct. Btw, how to command the bot on IRC?Could you please check the configs: https://pastebin.blesmrt.net/?391eba899180c153#83KKYnxCFFdaA1c1hsx6cAZRrK1dKRQ2rvw34a6xkshc
> remove "Bearer " from your auth token, or pull the latest update from the repo, I have just pushed an update which allows you to include the Bearer prefix

I did but still same...
