### ISSUE TITLE
Connect to IRC bouncer with password

### ISSUE THREAD

**Issue by simonpatap0n** [rj1/chatgpt-irc#8]
Hello. Thank you for your code!

i wanted to connect the bot to ZNC but it was missing password support on connection.

I did not want to create a PR because solution was asked to ChatGPT :>

`async def main_loop(**options):
    reader, writer = await asyncio.open_connection(
        host=options.get("server"), port=options.get("port"), ssl=options.get("ssl")
    )

    sendline = functools.partial(send_line_to_writer, writer)
    sendcmd = functools.partial(send_cmd_to_writer, writer)

    # Ajout du mot de passe pour le serveur IRC
    if options.get("password"):
        sendcmd("PASS", options.get("password"))

    sendline("NICK {nickname}".format(**options))
    sendline("USER {ident} * * :{realname}".format(**options))
`
I also added password field in config

`{
    "server": "",
    "port": 6667,
    "ssl": true,
    "nickname": "",
    "ident": "",
    "password": "",
    "realname": "",
    "channels": [""],
    "auth_token": "",
    "cookie": "",
    "useragent": ""
}
`

it's not really an issue I just wanted to help others in my situation fell free to close it

thank you again!

Simon

**Comment by rj1** [comment]
thanks! I'll add this

**Comment by rj1** [comment]
fixed via [74d2f68](https://github.com/rj1/chatgpt-irc/commit/74d2f68ecb78eb1be74b76275cd491d1bf4611f2)
